export enum ActionTypes {
  UPDATE_QUESTIONS = 'UPDATE_QUESTIONS',
  ADD_ANSWER = 'ADD_ANSWER',
  UPDATE_RECOMMENDATIONS = 'UPDATE_RECOMMENDATIONS',
  INITIALIZE_ANSWERS = 'INITIALIZE_ANSWERS',
  UPDATE_ANSWERS = 'UPDATE_ANSWERS',
}
